version: 2.1

executors:
  my-executor:
    environment:
      A_REPO: repoA
      B_REPO: repoB
      ECR_REPO_NAME: push-test

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

workflows:
  build-push-image:
    jobs:
      - aws-ecr/build-and-push-image:
          executor: my-executor
          machine: true
          context: research
          repo: $ECR_REPO_NAME
          tag: "${CIRCLE_TAG}"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^py.*/