name: Docker Image CI

on:
  push:
    tags:
      - "py*"
env:
  A_REPO: repoA
  B_REPO: repoB
  GITHUB_REPO_NAME: circleci-test
  IMAGE_NAME: push-test
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v3

    - name: Get Repository Release Version
      run: |
        echo "${{ secrets.TOKEN }}" | gh auth login --with-token
        echo "A_RELEASE_VERSION=$(gh api repos/${{ github.repository_owner }}/${{ env.A_REPO }}/releases/latest --jq '.tag_name')" >> $GITHUB_ENV
        echo "B_RELEASE_VERSION=$(gh api repos/${{ github.repository_owner }}/${{ env.B_REPO }}/releases/latest --jq '.tag_name')" >> $GITHUB_ENV

    - name: Set Environment Variables
      run: |
        A_RELEASE_VERSION=$(echo ${{ env.A_RELEASE_VERSION }} | sed 's/^v//')
        B_RELEASE_VERSION=$(echo ${{ env.B_RELEASE_VERSION }} | sed 's/^v//')
        echo "IMAGE_TAG=1.10.0-py3.7-v1-eval-${{ env.A_REPO }}-$A_RELEASE_VERSION-${{ env.B_REPO }}-$B_RELEASE_VERSION" >> $GITHUB_ENV

    - name: Print Environment Variables
      run: |
        echo "A_REPO: ${A_REPO}"
        echo "B_REPO: ${B_REPO}"
        echo "A_RELEASE_VERSION: ${{ env.A_RELEASE_VERSION }}"
        echo "B_RELEASE_VERSION: ${{ env.B_RELEASE_VERSION }}"
        echo "GITHUB_REPO_NAME: ${{ env.GITHUB_REPO_NAME }}"
        echo "IMAGE_NAME: ${{ env.IMAGE_NAME }}"
        echo "IMAGE_TAG: ${{ env.IMAGE_TAG }}"
        echo "github.actor: ${{ github.actor }}"
        echo "github.repository : ${{ github.repository }}"

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME}}:${{ env.IMAGE_TAG }}
        docker tag ${{ env.IMAGE_NAME}}:${{ env.IMAGE_TAG }} ghcr.io/${{ github.repository_owner }}/${{ env.GITHUB_REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Login to GitHub Container Registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push the Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/${{ env.GITHUB_REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
