name: Notify Slack

on:
  push:
    tags:
      - "test*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: github.event_name == 'push'
    steps:
      - name: Get current date
        run: echo "NOW=$(date +'%m/%d/%Y %T')" >> $GITHUB_ENV
      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL }}
          slack-message: "New tag pushed: ${{ github.ref }}"
          payload: |
            {
              "text": "Github Action workflow succeeded!",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Deployment Successful! :tada:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Project*: ${{ github.repository }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*When*: ${{ env.NOW }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Tag*: ${{ github.ref_name }}"
                    }
                  ],
                  "accessory": {
                    "type": "image",
                    "image_url": "https://avatars.githubusercontent.com/u/44036562",
                    "alt_text": "Github Action logo"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "action_id": "success_tagged_deploy_view",
                      "text": {
                        "type": "plain_text",
                        "text": "View workflow"
                      },
                      "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}